// Code generated by goctl. DO NOT EDIT.
package types

import (
	"github.com/zeromicro/go-zero/rest/httpx"
	"net/http"
)

type GetCaptchaRequest struct {
	Email       string `json:"email"`
	CaptchaType string `json:"captchaType"`
}

type GetCaptchaResponse struct {
	Code int32 `json:"code"`
}

type Body struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}

func Response(w http.ResponseWriter, resp interface{}, code int, msg string) {
	httpx.OkJson(w, Body{
		code,
		msg,
		resp,
	})
}
