// Code generated by goctl. DO NOT EDIT.
package types

type GetCaptchaRequest struct {
	Email string `json:"email"`
}

type GetCaptchaResponse struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}
