// Code generated by goctl. DO NOT EDIT.
// Source: captcha.proto

package server

import (
	"context"

	"giligili/app/captcha/rpc/internal/logic"
	"giligili/app/captcha/rpc/internal/svc"
	"giligili/app/captcha/rpc/pb"
)

type CaptchaServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCaptchaServiceServer
}

func NewCaptchaServiceServer(svcCtx *svc.ServiceContext) *CaptchaServiceServer {
	return &CaptchaServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CaptchaServiceServer) GetCaptchaByEmail(ctx context.Context, in *pb.GetCaptchaByEmailReq) (*pb.GetCaptchaByEmailResp, error) {
	l := logic.NewGetCaptchaByEmailLogic(ctx, s.svcCtx)
	return l.GetCaptchaByEmail(in)
}

func (s *CaptchaServiceServer) VerifyCaptcha(ctx context.Context, in *pb.VerifyCaptchaReq) (*pb.VerifyCaptchaResp, error) {
	l := logic.NewVerifyCaptchaLogic(ctx, s.svcCtx)
	return l.VerifyCaptcha(in)
}
