// Code generated by goctl. DO NOT EDIT.
// Source: email.proto

package server

import (
	"context"

	"giligili/app/email/rpc/internal/logic"
	"giligili/app/email/rpc/internal/svc"
	"giligili/app/email/rpc/pb"
)

type EmailServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedEmailServiceServer
}

func NewEmailServiceServer(svcCtx *svc.ServiceContext) *EmailServiceServer {
	return &EmailServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *EmailServiceServer) SendEmail(ctx context.Context, in *pb.SendEmailRequest) (*pb.SendEmailResponse, error) {
	l := logic.NewSendEmailLogic(ctx, s.svcCtx)
	return l.SendEmail(in)
}
