// Code generated by goctl. DO NOT EDIT.
// Source: email.proto

package emailservice

import (
	"context"

	"giligili/app/email/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SendEmailRequest  = pb.SendEmailRequest
	SendEmailResponse = pb.SendEmailResponse

	EmailService interface {
		SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error)
	}

	defaultEmailService struct {
		cli zrpc.Client
	}
)

func NewEmailService(cli zrpc.Client) EmailService {
	return &defaultEmailService{
		cli: cli,
	}
}

func (m *defaultEmailService) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error) {
	client := pb.NewEmailServiceClient(m.cli.Conn())
	return client.SendEmail(ctx, in, opts...)
}
